// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwtZh9GGR5N98M3suwn2DhpdWjUtMBVTs',
    appId: '1:97416754826:web:424db142746dfc6c919f73',
    messagingSenderId: '97416754826',
    projectId: 'fir-integration-7b2e9',
    authDomain: 'fir-integration-7b2e9.firebaseapp.com',
    storageBucket: 'fir-integration-7b2e9.firebasestorage.app',
    measurementId: 'G-VD7WYHRDCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5pm7WESU8e1iLov7YfF1-3yZzO3c4WTU',
    appId: '1:97416754826:android:c6af87c64fa57e41919f73',
    messagingSenderId: '97416754826',
    projectId: 'fir-integration-7b2e9',
    storageBucket: 'fir-integration-7b2e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfPoXaQvIyrJyW8oGOhgCJe9rzGpV39I0',
    appId: '1:97416754826:ios:af9b818c93d760c6919f73',
    messagingSenderId: '97416754826',
    projectId: 'fir-integration-7b2e9',
    storageBucket: 'fir-integration-7b2e9.firebasestorage.app',
    iosBundleId: 'com.example.sharedpref',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfPoXaQvIyrJyW8oGOhgCJe9rzGpV39I0',
    appId: '1:97416754826:ios:af9b818c93d760c6919f73',
    messagingSenderId: '97416754826',
    projectId: 'fir-integration-7b2e9',
    storageBucket: 'fir-integration-7b2e9.firebasestorage.app',
    iosBundleId: 'com.example.sharedpref',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwtZh9GGR5N98M3suwn2DhpdWjUtMBVTs',
    appId: '1:97416754826:web:28e4e3f7bdb04674919f73',
    messagingSenderId: '97416754826',
    projectId: 'fir-integration-7b2e9',
    authDomain: 'fir-integration-7b2e9.firebaseapp.com',
    storageBucket: 'fir-integration-7b2e9.firebasestorage.app',
    measurementId: 'G-0WHS41S77D',
  );
}
